# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-03 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_auto_20181103_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='dealerid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='goods',
            name='productid',
            field=models.CharField(max_length=20),
        ),
    ]
